// Daftar pertanyaan
const questions = [
"Keberuntungan lebih penting daripada kerja keras untuk meraih kesuksesan.",
"Keberuntungan adalah sesuatu yang bisa diciptakan, bukan sekadar kebetulan.",
"Orang yang selalu beruntung sebenarnya hanya pintar melihat peluang.",
"Kegagalan terjadi karena seseorang tidak cukup beruntung, bukan karena kurang usaha.",
"Orang pintar tapi tidak beruntung akan kalah dengan orang biasa yang beruntung.",
"Keberuntungan dalam cinta lebih penting daripada keberuntungan dalam karier.",
"Keberuntungan hanyalah mitos; semua pencapaian berasal dari usaha keras.",
"Anak tidak wajib membalas jasa orang tua jika merasa tidak pernah diperlakukan dengan baik.",
"Anak tidak harus mengikuti tradisi keluarga jika itu bertentangan dengan nilai hidupnya.",
"Keluarga tidak selalu menjadi tempat paling aman dan nyaman bagi seorang anak.",
"Anak berhak memilih pasangan hidup meskipun tidak disetujui oleh orang tua.",
"Bekerja dari rumah lebih produktif daripada bekerja di kantor.",
"Kebiasaan multitasking sebenarnya membuat pekerjaan jadi kurang efektif.",
"Orang yang sering memamerkan kehidupan sehari-hari di media sosial hanya mencari validasi.",
"Menabung terlalu banyak tanpa menikmati hidup adalah tindakan sia-sia.",
"Memperhatikan penampilan membuat seseorang lebih dihormati dalam pergaulan sehari-hari.",
"Visual lebih penting dibandingkan kepribadian.",
"Mengikuti tren demi diterima di lingkungan pertemanan itu penting.",
"Meminjamkan uang kepada teman adalah cara tercepat merusak hubungan.",
"Berhubungan baik dengan mantan saat sudah memiliki pasangan adalah tindakan yang wajar.",
"Kembali ke mantan adalah pilihan yang bodoh karena tidak akan berhasil lagi.",
  "Tidak ada yang salah dengan balikan ke mantan jika perasaan masih ada.",
"Menjalin komunikasi kembali dengan mantan saat sedang kesepian hal yang wajar.",
"Mantan bisa menjadi sahabat yang baik.",
"Mencari tahu kehidupan mantan setelah putus adalah hal yang tidak dewasa.",
"Bertemu mantan kembali setelah bertahun-tahun bisa membangkitkan perasaan lama.",
"Seseorang memprioritaskan karier daripada keluarga untuk mencapai kesuksesan.",
"Cinta habis di 1 orang.",
"LDR (Long Distance Relationship) tidak akan pernah berhasil.",
"Uang lebih penting daripada cinta dalam hubungan jangka panjang.",
"Selingkuh tanpa diketahui pasangan tidak akan merusak hubungan.",
"Pria harus selalu membayar setiap kali berkencan.",
"Mantan tidak bisa menjadi teman baik, apa pun situasinya.",
"Menikah hanya karena cinta adalah keputusan yang bodoh.",
"Seseorang menunggu mapan secara finansial walaupun umurnya sudah tua, lebih baik daripada menikah karena cinta dan waktu.",
"Keperawanan atau keperjakaan masih penting dalam hubungan sebelum menikah.",
"Cinta tidak cukup untuk mempertahankan sebuah hubungan.",
"Kehidupan seks yang tidak memuaskan adalah alasan sah untuk mengakhiri hubungan.",
"Hubungan yang sehat tidak membutuhkan label atau status resmi.",
"Cinta pada pandangan pertama itu nyata dan bisa bertahan lama.",
"Seseorang tidak perlu minta izin kepada pasangan untuk bertemu teman-temannya.",
"Pasangan harus selalu tahu keberadaan satu sama lain setiap saat.",
"Hubungan tanpa rencana menikah adalah buang-buang waktu.",
"Kebahagiaan pribadi lebih penting daripada menjaga hubungan.",
"Menunjukkan hubungan di media sosial wajib dilakukan untuk validasi saja.",
"Pria harus lebih mapan secara finansial daripada wanita dalam sebuah hubungan.",
"Perasaan cinta bisa berkembang meskipun awalnya tidak ada ketertarikan fisik.",
"Perasaan cinta tidak dapat berkembang walaupun dipaksakan dan diberi waktu.",
"Jika cinta sudah hilang, hubungan sebaiknya diakhiri tanpa memikirkan dampaknya.",
"Pasangan harus memiliki minat dan hobi yang sama.",
"Seseorang harus mendahulukan pasangan dibanding sahabat.",
"Pertemanan lebih penting daripada pasangan.",
"Ketidakcocokan dalam pendidikan dan status sosial tidak masalah dalam hubungan.",
"Cinta tidak bisa bertahan tanpa keintiman fisik.",
"Pasangan yang terlalu romantis lebih cepat bosan dalam hubungan.",
"Hubungan toxic lebih baik diperjuangkan daripada menyerah begitu saja.",
"Wajar seseorang rela mengubah dirinya agar sesuai dengan keinginan pasangan.",
"Wajar pasangan mengorbankan ambisi karier demi kebersamaan dalam hubungan.",
"Ketidakseimbangan cinta dalam hubungan (salah satu lebih cinta) tidak akan bertahan lama.",
"Pasangan yang tidak pernah bertengkar kemungkinan hubungannya tidak akan lama.",
"Jarak usia yang jauh tidak akan pernah menciptakan hubungan yang setara.",
"Menikahi seseorang atas dasar aman secara finansial lebih realistis daripada karena cinta.",
"Cinta bisa tumbuh karena rasa kasihan atau belas kasih.",
"Hubungan tanpa seks tidak akan pernah langgeng.",
"Hubungan bisa bertahan meskipun tidak ada rasa cinta, asalkan ada komitmen.",
"Perselingkuhan emosional lebih buruk daripada perselingkuhan fisik.",
"Pasangan yang lebih sukses secara finansial akan selalu memegang kendali dalam hubungan.",
"Hubungan sebaiknya diakhiri jika pasangan tidak disukai oleh keluarga.",
"Perempuan lebih sering dimanfaatkan dalam hubungan daripada laki-laki.",
"Seseorang tidak perlu menikah untuk menunjukkan kesetiaan dalam hubungan.",
"Kejujuran total dalam hubungan justru bisa menghancurkan hubungan.",
"Seseorang yang tidak ingin punya anak sebaiknya tidak menikah.",
"Memutuskan pasangan melalui pesan teks adalah hal yang wajar.",
"Pasangan harus selalu meminta izin sebelum memutuskan sesuatu.",
"Tidak masalah jika seseorang tetap dekat dengan mantannya.",
"Hubungan tidak akan berhasil jika salah satu pihak memiliki lebih banyak pengalaman cinta sebelumnya.",
"Pasangan tidak wajib memberi tahu penghasilannya kepada satu sama lain.",
"Ketertarikan fisik lebih penting daripada kecocokan karakter dalam hubungan.",
"Pasangan yang jarang berkomunikasi lebih mungkin memiliki hubungan yang sehat.",
"Memprioritaskan diri sendiri di atas pasangan adalah tanda cinta yang sehat.",
"Menyukai lebih dari satu orang saat PDKT adalah hal yang wajar.",
"Jika seseorang terlalu sulit didekati, lebih baik menyerah daripada berusaha keras.",
"Seseorang yang terlalu sering memuji saat PDKT dianggap tidak tulus.",
"PDKT sebaiknya tidak dilakukan terlalu lama, karena membuang waktu.",
"Mengungkapkan perasaan terlalu cepat saat PDKT adalah tanda ketidakdewasaan.",
"Seseorang tidak perlu jujur sepenuhnya tentang masa lalunya selama PDKT.",
"Mengobrol setiap hari saat PDKT akan membuat seseorang cepat bosan.",
"Menjadi ‘friendly’ adalah strategi yang salah saat PDKT.",
"Mengungkapkan perasaan cinta di awal PDKT adalah hal yang berani dan sah dilakukan.",
"Tidak ada salahnya mendekati lebih dari satu orang secara bersamaan.",
"Seseorang harus menunjukkan rasa cemburu saat PDKT untuk menunjukkan keseriusan.",
"PDKT hanya boleh dilakukan jika sudah yakin akan menuju hubungan yang serius.",
"Seharusnya memutuskan hubungan harus bertemu langsung, bukan melalui pesan teks.",
"Putus cinta lebih baik dilakukan secara tiba-tiba daripada secara perlahan (perlakuan berubah, menghilang, berantem, dll).",
"Mengakhiri hubungan tanpa memberi alasan.",
"Seseorang harus tetap berteman dengan mantannya setelah putus.",
"Putus cinta karena tekanan dari keluarga adalah keputusan yang tepat.",
"Putus cinta karena alasan finansial lebih realistis daripada karena perasaan semata.",
"Putus cinta karena pasangan tidak sesuai dengan ekspektasi fisik.",
"Putus cinta tanpa adanya kesalahan dari salah satu pihak.",
"Putus cinta dilakukan secara perlahan untuk mengurangi rasa sakit.",
"Melibatkan pihak ketiga untuk membantu proses putus cinta.",
"Mengakhiri hubungan tanpa status tidak membutuhkan penjelasan atau alasan.",
"Menjalani hubungan tanpa status cenderung lebih dari satu orang.",
"Hubungan tanpa status lebih sulit dipertahankan daripada hubungan resmi.",
"Salah satu pihak dalam hubungan tanpa status pasti akan jatuh cinta pada akhirnya.",
"Hubungan tanpa status tidak bisa bertahan lama tanpa keintiman fisik.",
"Teman lebih penting daripada pasangan.",
"Memutuskan hubungan dengan teman lebih sulit daripada dengan pasangan.",
"Lebih baik memiliki satu teman sejati daripada banyak teman.",
"Tidak ada salahnya meminjam uang dari teman tanpa membayar tepat waktu.",
"Persahabatan pria dan wanita tidak akan pernah benar-benar murni tanpa ada perasaan cinta.",
"Persahabatan yang melibatkan bisnis lebih rentan rusak.",
"Memprioritaskan pasangan daripada teman.",
"Teman yang selalu berkata jujur lebih berharga daripada teman yang selalu mendukung.",
"Menjadikan teman sebagai prioritas utama bisa merusak hubungan dengan pasangan.",
"Seseorang tidak harus selalu memaafkan kesalahan teman.",
"Teman yang sering bercanda kasar lebih peduli daripada teman yang selalu serius.",
"Teman yang lebih kaya atau sukses cenderung lebih dominan dalam pertemanan.",
"Pada akhirnya manusia memilih teman berdasarkan status sosial atau ekonomi.",
"Manusia berteman karena ada kepentingan bersama.",
"Pertemanan bertahan karena ada di lingkungan yang sama.",
"Tidak ada salahnya berteman untuk mendapatkan sesuatu.",
"Tidak masalah menjalin pertemanan karena ingin mendapatkan keuntungan pribadi.",
"Teman yang hanya datang saat butuh bantuan bukanlah hal yang salah, itu bagian dari dinamika sosial.",
"Secara realistis, seseorang tidak akan berteman dengan strata sosialnya lebih dibawah.",
"Uang adalah sumber kebahagiaan.",
"Terlalu sering meminta maaf bisa membuat orang lain tidak menghargai kita.",
"Keberhasilan seseorang lebih dipengaruhi oleh keberuntungan daripada usaha keras.",
"Mengambil keputusan besar dalam hidup berdasarkan perasaan lebih baik daripada berdasarkan logika.",
"Orang yang terlalu baik sering kali dianggap lemah atau tidak dihargai.",
"Seseorang tidak perlu jujur tentang masa lalu mereka jika itu akan menyakiti pasangannya.",
"Menilai orang dari penampilan adalah hal yang wajar.",
"Visual seseorang sangatlah penting.",
"Orang yang tidak pernah mengalami kegagalan tidak akan bisa sukses dengan baik.",
"Persahabatan antara pria dan wanita tanpa ada perasaan cinta adalah hal yang mustahil.",
"Menjaga jarak dengan keluarga adalah keputusan yang sah-sah saja jika itu demi kesejahteraan pribadi.",
"Mengubah penampilan fisik demi orang lain adalah hal yang wajar.",
"Pernikahan yang tidak disetujui keluarga seharusnya dibatalkan.",
"Kehidupan pribadi anak tidak perlu diketahui oleh orang tua.",
"Anak-anak tidak boleh diberi akses ke gadget sebelum usia 10 tahun.",
"Sistem kapitalisme adalah penyebab utama kesenjangan sosial di dunia.",
"Kesehatan mental sama pentingnya seperti kesehatan fisik.",
"Memaafkan dengan cara melupakan kesalahan sebelumnya adalah hal yang wajar.",
"Mendukung seni kontroversial yang menghina agama atau budaya adalah bentuk kebebasan berekspresi.",
"Jokes perihal agama, ras, kontroversial lainnya adalah perbuatan kurang baik.",
"Hidup bahagia lebih penting daripada hidup bermoral.",
"Meninggalkan pasangan demi kebahagiaan pribadi adalah hal yang bisa dibenarkan.",
"Berhubungan seksual sebelum menikah adalah hak pribadi yang tidak boleh dihakimi.",
"Memiliki lebih dari satu pasangan seksual sekaligus adalah hal yang normal selama ada kesepakatan bersama.",
"Menggunakan aplikasi kencan untuk mencari pasangan seksual bukanlah sesuatu yang memalukan.",
"Berbicara secara terbuka tentang fantasi seksual dengan pasangan adalah tanda hubungan yang sehat.",
"Menjaga hubungan terbuka (open relationship) adalah solusi untuk mencegah perselingkuhan.",
"Budaya lokal yang melanggar hak asasi manusia seharusnya dihapus tanpa kompromi.",
"Memblokir seseorang di media sosial tanpa memberi penjelasan adalah tindakan yang bisa dibenarkan.",
"Berbohong kepada pasangan demi menghindari pertengkaran adalah wajar.",
"Bermesraan ditempat umum hal wajar.",
"Jika pasangan tidak lagi menarik secara fisik, mencintai mereka sepenuhnya menjadi lebih sulit.",
"Menyembunyikan kesuksesan finansial dari teman dekat adalah langkah bijak untuk menjaga hubungan.",
"Membatalkan janji dengan alasan kesehatan mental sama validnya dengan alasan fisik.",
"Tidak semua orang layak diberi kesempatan kedua, termasuk keluarga sendiri.",
"Meninggalkan grup keluarga di aplikasi pesan tanpa penjelasan bukanlah tindakan yang salah.",
"Menyimpan rahasia pribadi dari pasangan tidak akan memengaruhi hubungan.",
"Meminjam uang kepada teman lebih baik daripada meminjam dari keluarga.",
"Membeli barang mewah saat masih punya utang adalah keputusan yang dapat dibenarkan untuk kebahagiaan diri.",
"Memprioritaskan pekerjaan dibandingkan keluarga adalah hal yang wajar.",
"Mengabaikan pesan dari teman lama lebih baik daripada memulai percakapan yang menggantung.",
"Meminta uang tambahan kepada orang tua di usia dewasa hal yang wajar.",
"Membatalkan janji dengan alasan ‘tidak mood’ adalah hal yang dapat diterima.",
"Tidak perlu merasa bersalah jika tidak memberi kabar kepada teman yang tidak menghubungi kita duluan.",
"Menjaga hubungan dengan teman hanya karena sudah lama mengenal mereka walaupun tidak mendapatkan benefit.",
"Menceritakan hal pribadi kepada teman adalah tidak berguna.",
"Wajar untuk memutuskan hubungan pertemanan, karena dianggap teman tersebut tidak berkembang walaupun itu teman dekat kamu.",
"Menghidari teman yang suka mengeluh.",
"Memberi nasihat kepada teman walaupun tidak diminta.",
"Memilih teman berdasarkan status sosial.",
  "Mengurangi komunikasi dengan teman yang tidak sejalan.",
"Lebih baik mempertahankan teman lama daripada mencari teman baru.",
"Orang yang sukses di usia muda sering kali mengorbankan kebahagiaan hidupnya.",
"Anak-anak yang dibesarkan dengan keras lebih siap menghadapi kehidupan.",
"Manusia tidak pernah bisa benar-benar berubah, apa pun yang mereka lakukan.",
"Memegang teguh prinsip hidup jauh lebih penting daripada menyesuaikan diri dengan perubahan zaman.",
"Tidak ada yang namanya pekerjaan impian; pekerjaan hanyalah cara untuk bertahan.",
"Mengejar uang lebih penting daripada mengejar jenjang karier.",
"Seseorang harus rela mengorbankan waktu bersama keluarga demi mencapai puncak karier.",
"Uang yang banyak lebih berharga daripada jabatan tinggi.",
"Jenjang karier tidak penting jika kebutuhan finansial sudah terpenuhi.",
"Bekerja hanya demi uang.",
"Lebih baik mengambil pekerjaan dengan gaji besar meskipun tidak sesuai dengan jenjang karir yang telah dibangun/inginkan.",
"Orang yang hanya mengejar jenjang karier cenderung lupa menikmati hidup.",
"Uang yang cukup lebih baik daripada stres akibat tanggung jawab besar di pekerjaan (walaupun besar juga bayarannya).",
"Kehidupan yang stabil lebih penting daripada ambisi mengejar karier.",
"Atasan yang tegas lebih baik daripada atasan yang terlalu ramah.",
"Lingkungan kerja yang toxic seharusnya ditinggalkan meskipun gajinya tinggi.",
"Bekerja untuk passion lebih penting daripada mendapatkan gaji besar.",
"Menjilat atasan adalah strategi karier yang sah-sah saja.",
"Anak pertama selalu diberi tanggung jawab lebih besar dibandingkan saudara lainnya.",
"Anak memilih jalan hidup berbeda dari tradisi keluarga.",
"Anak seharusnya tidak wajib mengikuti agama yang dianut keluarganya.",
"Jika sudah bekerja, anak harus membantu keuangan keluarga.",
"Perbedaan agama dalam pernikahan tidak akan memengaruhi keharmonisan rumah tangga.",
"Seseorang tidak perlu menjalankan ritual agama untuk dianggap beriman.",
"Memaksakan keyakinan agama kepada orang lain adalah tindakan yang dapat dibenarkan.",
"Pendidikan agama di sekolah seharusnya bersifat netral dan tidak mengajarkan satu agama saja.",
"Seseorang yang berbuat baik tanpa agama memiliki nilai yang sama dengan orang beragama yang berbuat baik.",
"Ateisme adalah pilihan yang harus dihormati sama seperti pilihan untuk beragama.",
"Seorang anak pindah agama.",
"Seseorang pindah agama hanya untuk syarat berkeluarga.",
"Anak-anak seharusnya diberi kebebasan untuk memilih agamanya sendiri.",
"Mengkritik agama tertentu bukanlah tindakan intoleransi.",
"Perbedaan tafsir dalam agama sering kali lebih memecah belah daripada menyatukan, walaupun dalam agama yang sama.",
"Agama lebih sering digunakan untuk kepentingan pribadi daripada tujuan kebaikan bersama.",
"Memilih untuk tidak memilih dalam pemilu adalah bentuk kebebasan demokrasi.",
"Pemimpin korupsi, namun pemimpin tersebut berhasil memajukan negara tersebut.",
"Partai politik seharusnya dibatasi jumlahnya untuk menghindari perpecahan suara.",
"Hukuman mati layak diberikan.",
"Pemerintah berhak membatasi kebebasan berbicara demi menjaga stabilitas negara.",
"Politisi yang sering berganti partai menunjukkan bahwa mereka tidak punya prinsip.",
"Sejarah selalu ditulis oleh pemenang, sehingga kebenarannya sering bias.",
"Pahlawan dalam sejarah sebenarnya hanyalah tokoh yang diuntungkan oleh propaganda.",
"Peristiwa sejarah yang dihafalkan di sekolah tidak relevan dengan kehidupan modern.",
"Kesetaraan gender hanya diuntungkan untuk pihak perempuan saja.",
"Pria cenderung lebih logis, sedangkan wanita lebih emosional dalam mengambil keputusan.",
"Wanita lebih baik dalam multitasking dibanding pria.",
"Pria memiliki tanggung jawab yang lebih besar dalam mencari nafkah dibanding wanita.",
"Wanita lebih mudah mengungkapkan perasaan dibanding pria.",
"Pria lebih baik dalam memimpin dibanding wanita.",
"Wanita lebih peduli dengan penampilan dibanding pria.",
"Pria lebih sulit menunjukkan kasih sayang dibanding wanita.",
"Wanita lebih sering mengandalkan perasaan, sementara pria lebih mengutamakan logika.",
"Pria lebih tahan banting dalam menghadapi masalah emosional daripada wanita.",
"Pria lebih cenderung berpikir jangka panjang.",
"Pria lebih suka menyelesaikan masalah sendirian, sementara wanita lebih terbuka untuk berdiskusi.",
"Pria yang berkarier sukses harus mengorbankan kehidupan pribadi, dibandingkan wanita.",
"Wanita lebih mudah terpengaruh oleh tren dan opini orang lain.",
"Pria yang emosional dianggap kurang matang, sedangkan wanita dianggap lebih manusiawi.",
"Wanita lebih bisa menjaga hubungan persahabatan jangka panjang dibanding pria.",
"Pria lebih mementingkan kebebasan pribadi, sementara wanita lebih cenderung mencari kestabilan.",
"Wanita lebih rentan terhadap tekanan sosial tentang penampilan daripada pria.",
"Pria lebih cenderung mengambil risiko yang lebih besar daripada wanita.",
"Wanita lebih pintar dalam mengelola waktu antara pekerjaan dan kehidupan pribadi.",
"Pria lebih suka mengambil keputusan cepat tanpa banyak pertimbangan, sedangkan wanita lebih berhati-hati.",
"Wanita lebih sulit untuk benar-benar melupakan masa lalu dalam hubungan daripada pria.",
"Pria lebih mudah beradaptasi dengan perubahan dalam hidup daripada wanita.",
"Wanita lebih sering dihargai karena penampilan mereka, sedangkan pria lebih dihargai karena pencapaian mereka.",
"Pria dilihat dari harta, wanita dilihat dari penampilan.",
"Pekerjaan rumah tangga seharusnya dibagi rata antara suami dan istri, tidak hanya menjadi tanggung jawab wanita. Walaupun suami yang mencari nafkah.",
"Pria yang menangis dianggap lebih lemah, sementara wanita yang menunjukkan ketegasan dianggap terlalu galak.",
  "Seks bebas tanpa komitmen adalah hal yang wajar di era sekarang.",
"Di era sekarang, tetap seks pertama kali harus terjadi dalam pernikahan.",
"Dalam konteks hubungan 'Jalanin dulu aja, kita liat kedepannya gimana'.",
"Pasangan yang sudah tinggal bersama sebelum menikah lebih cocok untuk menghadapi kenyataan kehidupan.",
"Pacaran di era sekarang lebih dipengaruhi oleh ekspektasi sosial dan tren daripada perasaan sejati.",
"Hubungan pacaran harus selalu terbuka, tidak ada yang boleh disembunyikan.",
"Hubungan pacaran yang penuh drama lebih menarik.",
"Menunjukkan kehidupan pribadi di media sosial adalah bentuk mencari perhatian.",
"Jika seseorang menjadi publik figur, mereka harus siap untuk hidup di bawah sorotan dan kehilangan privasi.",
"Seseorang yang memposting kehidupan pribadi mereka di media sosial tidak boleh mengeluh jika ada yang mengomentari negatif.",
"Orang yang terlihat bahagia, padahal dibelakangnya terjadi banyak masalah.",
"Keberagaman budaya harus dilestarikan meskipun itu bertentangan dengan perkembangan teknologi global.",
"Seni yang menggambarkan kekerasan tidak dapat memicu perilaku kekerasan di dunia nyata.",
"Seni yang terlalu eksperimental tidak seharusnya dianggap seni.",
"Seni seharusnya dapat dipahami oleh semua orang, bukan hanya kalangan tertentu.",
"Kata 'Seni' menjadi tameng terhadap terjadinya unsur SARA.",
"Membatasi Kebebasan Berbicara di Internet.",
  
];
// Menampilkan pertanyaan secara acak
function showRandomQuestion() {
  const randomIndex = Math.floor(Math.random() * questions.length);
  const questionText = questions[randomIndex];
  document.querySelector(".question").textContent = questionText;
}

// Mengubah pertanyaan ketika tombol "NEXT CARD" ditekan
document.getElementById("next-btn").addEventListener("click", showRandomQuestion);

// Menampilkan pertanyaan pertama saat halaman dimuat
window.onload = showRandomQuestion;

