// Daftar pertanyaan
const questions = [
    "Kebebasan berbicara seharusnya tidak memiliki batas, bahkan jika itu menyinggung kelompok tertentu.",
    "Hukuman mati adalah solusi yang sah untuk kejahatan berat.",
    "Manusia seharusnya tidak mencoba memanipulasi genetik untuk menciptakan “manusia sempurna.”",
    "Perubahan iklim lebih banyak disebabkan oleh perilaku manusia daripada siklus alami bumi.",
    "Kekayaan dunia terlalu banyak terpusat di tangan segelintir orang.",
    "Perkembangan kecerdasan buatan pada akhirnya akan mengancam eksistensi manusia.",
    "Media sering kali memanipulasi opini publik untuk mendukung kepentingan tertentu.",
    "Perang terkadang diperlukan untuk menciptakan perdamaian yang abadi.",
    "Pendidikan gratis untuk semua orang adalah hak fundamental manusia.",
    "Kebijakan pembatasan kelahiran seharusnya diterapkan di negara-negara dengan populasi yang terlalu besar.",
    "Agama sering kali lebih memecah belah daripada menyatukan umat manusia.",
    "Negara kaya memiliki kewajiban moral untuk membantu negara miskin.",
    "Perbedaan budaya tidak seharusnya dijadikan alasan untuk mempertahankan tradisi yang melanggar hak asasi manusia.",
    "Hak untuk memiliki senjata api lebih banyak membawa bahaya daripada perlindungan.",
    "Penebangan hutan untuk memenuhi kebutuhan manusia tidak bisa dihindari.",
    "Orang kaya seharusnya membayar pajak lebih tinggi untuk mendukung kesejahteraan sosial.",
    "Eutanasia (hak untuk mati) adalah hak yang seharusnya dimiliki setiap manusia.",
    "Privasi individu sering kali dikorbankan secara tidak adil demi keamanan nasional.",
    "Negara seharusnya tidak ikut campur dalam keputusan reproduksi individu, termasuk aborsi.",
    "Kolonialisme modern masih berlangsung dalam bentuk kontrol ekonomi global.",
    "Perkawinan sesama jenis seharusnya diakui secara global tanpa syarat.",
    "Penggunaan hewan untuk pengujian medis dan kosmetik seharusnya dilarang sepenuhnya.",
    "Teknologi seperti kamera pengawas menciptakan dunia yang lebih aman, meskipun merusak privasi.",
    "Pendidikan agama seharusnya tidak diajarkan di sekolah-sekolah negeri.",
    "Kebebasan ekonomi sering kali menciptakan ketidakadilan yang lebih besar daripada kesejahteraan.",
    "Kehidupan di planet lain lebih mungkin ditemukan daripada keberadaan Tuhan.",
    "Setiap negara memiliki hak untuk menutup perbatasannya dari imigrasi.",
    "Kebijakan afirmasi untuk kelompok yang terpinggirkan lebih banyak merugikan daripada membantu.",
    "Teknologi cloning manusia tidak boleh dikembangkan, bahkan untuk alasan medis.",
    "Anak-anak tidak seharusnya dipaksa mengikuti tradisi budaya atau agama orang tua mereka.",
    "Keberhasilan individu lebih banyak bergantung pada faktor keberuntungan daripada kerja keras.",
    "Teknologi telah lebih banyak merugikan daripada menguntungkan umat manusia.",
    "Setiap orang berhak mendapatkan kekayaan yang tak terbatas, terlepas dari bagaimana mereka mendapatkannya.",
    "Kapitalisme adalah sistem yang lebih adil daripada sosialisme.",
    "Pemerintah seharusnya tidak memiliki hak untuk mengatur kehidupan pribadi warganya.",
    "Pendidikan formal lebih membatasi kreativitas daripada mengembangkannya.",
    "Agama seharusnya tidak lagi memiliki peran dalam kehidupan politik dan sosial.",
    "Perlindungan hak asasi manusia harus lebih diutamakan daripada keamanan nasional.",
    "Ketidaksetaraan gender adalah masalah yang lebih kompleks daripada sekadar perjuangan hak-hak perempuan.",
    "Globalisasi lebih banyak merusak budaya lokal daripada memberikan manfaat.",
    "Cinta sejati hanya bisa ditemukan setelah seseorang benar-benar merasa bahagia dengan diri sendiri.",
    "Tidak ada hubungan yang bisa bertahan tanpa pengorbanan besar dari kedua belah pihak.",
    "Perbedaan pandangan politik atau agama adalah alasan yang sah untuk mengakhiri hubungan romantis.",
    "Kepercayaan itu mudah dibangun, tetapi sangat sulit untuk dipertahankan dalam hubungan jangka panjang.",
    "Seseorang bisa mencintai lebih dari satu orang pada saat yang bersamaan tanpa itu mengurangi kualitas hubungan.",
    "Hubungan yang sehat adalah hubungan di mana kedua belah pihak memiliki kebebasan untuk mengejar impian pribadi, bahkan jika itu mengorbankan hubungan.",
    "Cemburu dalam hubungan adalah tanda cinta yang sehat, jika itu dilakukan dalam batas wajar.",
    "Ketika pasangan tidak setuju dengan keputusan besar dalam hidup, itu adalah tanda bahwa hubungan tersebut tidak dapat berkembang.",
    "Percintaan yang dimulai dari persahabatan lebih berisiko gagal dibandingkan percintaan yang dimulai dari ketertarikan fisik.",
    "Hubungan yang penuh konflik lebih bermanfaat dalam jangka panjang daripada hubungan yang selalu damai.",
    "Seringkali, lebih baik mengakhiri hubungan jika salah satu pasangan tidak bisa berkompromi.",
    "Ketika hubungan sudah terasa monoton, salah satu pasangan berhak mencari kebahagiaan di luar hubungan.",
    "Pernikahan bukanlah solusi untuk mengatasi masalah dalam hubungan, justru bisa memperburuk keadaan.",
    "Orang seharusnya tidak terlalu mengandalkan pasangan mereka untuk kebahagiaan pribadi.",
    "Ketika pasanganmu berubah menjadi seseorang yang berbeda, kamu berhak untuk memilih apakah akan tetap bersama atau tidak.",
    "Perselingkuhan bisa dimaafkan jika pasangan menunjukkan penyesalan yang tulus dan berusaha memperbaiki hubungan.",
    "Mempunyai hubungan dengan lebih dari satu orang sekaligus (polyamory) adalah hal yang sah dan tidak salah secara moral.",
    "Orang yang terlalu bergantung pada pasangan untuk kebahagiaannya cenderung menghambat perkembangan pribadi mereka.",
    "Mengungkapkan perasaan terlalu banyak dalam hubungan bisa membuat pasangan merasa tertekan.",
    "Tidak perlu selalu setuju dengan pasangan tentang segala hal untuk memiliki hubungan yang sehat.",
    "Seorang teman yang benar-benar peduli tidak akan pernah meninggalkan kita, apa pun yang terjadi.",
    "Persahabatan sejati tidak mungkin terjadi jika ada perasaan iri antara teman.",
    "Persahabatan bisa bertahan meskipun salah satu pihak pernah berkhianat.",
    "Uang dan persahabatan tidak boleh dicampur; salah satu pasti akan hancur.",
    "Dalam persahabatan, kejujuran lebih penting daripada menjaga perasaan.",
    "Terkadang, lebih baik memutuskan hubungan dengan teman yang tidak lagi sejalan dengan kita.",
    "Persahabatan jarak jauh biasanya tidak akan bertahan lama.",
    "Teman yang baik harus selalu mendukung keputusan kita, bahkan jika itu salah.",
    "Memilih teman berdasarkan status sosial atau keuangan adalah hal yang wajar.",
    "Teman lama lebih berharga daripada teman baru, meskipun tidak lagi sering berkomunikasi.",
    "Terkadang, orang yang kita anggap teman hanya memanfaatkan kita untuk keuntungan pribadi mereka.",
    "Dalam pertemanan, membicarakan teman di belakang mereka adalah hal yang tidak bisa dihindari.",
    "Lebih baik memiliki banyak teman yang dangkal daripada hanya satu teman yang benar-benar dekat.",
    "Teman dari lawan jenis biasanya akan menimbulkan masalah jika salah satu mulai memiliki perasaan romantis.",
    "Memutuskan pertemanan karena perbedaan pandangan politik atau agama adalah hal yang dapat dibenarkan.",
    "Teman yang terlalu jujur cenderung lebih banyak menyakiti daripada membantu.",
    "Tidak semua teman layak diberi kesempatan kedua setelah mereka melakukan kesalahan besar.",
    "Ketika kita sukses, teman sejati adalah mereka yang tetap mendukung tanpa merasa iri.",
    "Teman seharusnya selalu mendahulukan kita dibandingkan dengan hubungan romantis mereka.",
    "Teman yang sering meminjam uang dan tidak mengembalikannya lebih baik dihindari.",
    "Dalam persahabatan, loyalitas lebih penting daripada kejujuran.",
    "Teman yang berubah karena pengaruh pasangan mereka bukanlah teman sejati.",
    "Tidak semua teman layak diajak untuk berbagi masalah pribadi.",
    "Teman yang berbeda latar belakang budaya sulit untuk memahami kita sepenuhnya.",
    "Teman yang terlalu sering mengkritik kita sebenarnya tidak tulus dalam persahabatan.",
    "Persahabatan tidak bisa bertahan jika salah satu pihak tidak mau berkompromi.",
    "Membatalkan rencana dengan teman demi pekerjaan adalah hal yang dapat dibenarkan.",
    "Teman yang hanya hadir saat kita sedang senang seharusnya tidak dianggap teman sejati.",
    "Terkadang, kita harus membatasi hubungan dengan teman yang terlalu bergantung secara emosional.",
    "Persahabatan dengan mantan pasangan romantis hampir selalu akan menimbulkan masalah.",
    "Cinta tidak harus selalu dibalas untuk dianggap tulus.",
    "Ketidaksetiaan dalam hubungan bisa dimaafkan jika masih ada cinta.",
    "Pasangan memiliki hak untuk mengetahui setiap aspek kehidupan pribadi kita.",
    "Hubungan tanpa pernikahan lebih fleksibel dan sehat dibandingkan hubungan yang diikat pernikahan.",
    "Perbedaan agama dalam hubungan lebih sering menjadi penyebab konflik daripada pengayaan.",
    "Pasangan harus memiliki akses ke media sosial masing-masing untuk membangun kepercayaan.",
    "Ketidaksetaraan penghasilan antara pasangan bisa menjadi penyebab utama keretakan hubungan.",
    "Tidak ada yang salah dengan menjalin hubungan demi keuntungan finansial.",
    "Hubungan yang sehat membutuhkan salah satu pihak untuk mendominasi.",
    "Dalam hubungan, mempertahankan kebebasan pribadi lebih penting daripada mengikuti keinginan pasangan.",
    "Seks adalah komponen yang lebih penting daripada cinta dalam hubungan jangka panjang.",
    "Pasangan yang tidak bisa memenuhi kebutuhan emosional kita sebaiknya digantikan.",
    "Hubungan jarak jauh lebih banyak membawa penderitaan daripada kebahagiaan.",
    "Tidak ada salahnya memiliki hubungan terbuka selama kedua pihak setuju.",
    "Perbedaan pandangan politik yang ekstrem tidak seharusnya menjadi penghalang dalam hubungan.",
    "Pasangan harus selalu mengutamakan keluarga mereka dibandingkan pasangannya.",
    "Ketertarikan fisik lebih penting daripada kecocokan emosional dalam awal hubungan.",
    "Menikah untuk memenuhi harapan keluarga lebih baik daripada hidup sendiri.",
    "Pasangan yang tidak sepaham tentang memiliki anak seharusnya tidak melanjutkan hubungan.",
    "Percintaan masa lalu harus selalu diceritakan kepada pasangan untuk menjaga kejujuran.",
  "Cinta sejati hanya terjadi sekali seumur hidup.",
"Pasangan yang saling mencintai tidak perlu memberi ruang pribadi satu sama lain.",
"Pasangan yang hidup terpisah lebih bahagia daripada yang tinggal bersama.",
"Hubungan romantis yang dimulai dari persahabatan jarang berakhir bahagia.",
"Jika pasanganmu tidak mendukung impianmu, itu adalah tanda hubungan yang tidak sehat.",
"Cemburu adalah tanda cinta yang sehat dalam hubungan.",
"Orang yang sudah menikah tidak seharusnya memiliki teman dekat dari lawan jenis.",
"Pasangan yang menikah harus memiliki tujuan hidup yang sepenuhnya serupa.",
"Perselingkuhan emosional lebih merusak hubungan daripada perselingkuhan fisik.",
"Pernikahan tidak selalu menjadi solusi untuk hubungan yang bermasalah.",
"Setiap pasangan seharusnya memiliki hak untuk 'beristirahat' atau 'berpisah' sementara tanpa berakhir pada perceraian.",
"Ketika satu pasangan merasa lebih superior, hubungan itu akan mengalami masalah besar.",
"Menikah lebih penting daripada tinggal bersama tanpa status resmi.",
"Pasangan yang tidak pernah berdebat atau bertengkar tidak benar-benar saling mengenal.",
"Keberhasilan hubungan lebih banyak bergantung pada kebetulan daripada usaha bersama.",
"Pasangan yang tidak setuju dalam hal keuangan seharusnya tidak melanjutkan hubungan.",
"Hubungan yang sehat membutuhkan salah satu pihak untuk mengalah lebih sering daripada yang lain.",
"Orang seharusnya tidak memiliki harapan tinggi terhadap pasangan mereka dalam hubungan.",
"Setiap orang berhak mencari kebahagiaan di luar hubungan mereka jika merasa tidak puas.",
"Semua hubungan berakhir dengan patah hati atau kekecewaan.",
"Pasangan yang tidak sepaham tentang anak seharusnya tidak melanjutkan hubungan.",
"Hidup berkeluarga adalah langkah yang lebih penting daripada pencapaian karier.",
"Pasangan yang memiliki perbedaan budaya tidak bisa benar-benar memahami satu sama lain.",
"Tidak ada alasan untuk tetap bertahan dalam hubungan yang toksik, bahkan jika sudah lama bersama.",
"Menyimpan rahasia kecil dari pasangan bukanlah masalah besar dalam hubungan.",
"Cinta tidak cukup untuk menjaga hubungan jangka panjang, kebutuhan material juga penting.",
"Semua pasangan memiliki waktu di mana mereka merasa bosan satu sama lain.",
"Setiap hubungan harus memiliki peraturan atau batasan yang jelas agar bisa bertahan.",
"Pasangan yang tidak pernah mengungkapkan perasaan mereka mungkin memiliki masalah dalam hubungan.",
"Ketika satu pasangan berkembang secara pribadi, itu sering menantang dinamika hubungan.",
"Hubungan yang ideal adalah hubungan di mana pasangan bisa hidup secara terpisah tetapi tetap merasa terhubung.",
"Tidak ada yang salah dengan memiliki lebih dari satu pasangan romantis jika semua pihak setuju.",
"Mengorbankan kebahagiaan pribadi demi kebahagiaan pasangan adalah hal yang wajar dalam hubungan.",
"Tidak ada yang salah dengan pasangan yang tidak memiliki ketertarikan fisik lagi satu sama lain setelah bertahun-tahun bersama.",
"Hubungan jarak jauh hanya berhasil jika kedua belah pihak sepenuhnya setia.",
"Menikah pada usia muda seringkali tidak memberikan waktu untuk pengembangan pribadi.",
"Pasangan yang saling mencintai harus selalu berbagi setiap detail hidup mereka.",
"Menghormati perasaan keluarga lebih penting daripada menjaga hubungan romantis kita.",
"Pasangan yang terlalu mirip tidak akan bertahan lama.",
"Ketika pasanganmu tidak mendukung karier atau aspirasi kamu, itu adalah bentuk kekurangan rasa hormat.",
"Mencintai diri sendiri lebih penting daripada mencintai pasangan.",
"Pasangan yang selalu mengatur hidupmu akan menyebabkan ketergantungan yang tidak sehat.",
"Setiap hubungan perlu adanya 'ruang bebas' untuk menjaga kedamaian.",
"Tidak ada hubungan yang bisa bertahan jika ada ketidakjujuran besar, meskipun itu demi kebaikan pasangan.",
"Seks adalah bagian yang lebih penting dari komunikasi dalam hubungan.",
"Mengubah diri demi pasangan adalah tanda cinta yang besar, meskipun bisa merugikan diri sendiri.",
"Menjaga hubungan tetap segar adalah usaha yang lebih besar daripada menciptakan cinta baru.",
"Pasangan yang tidak sepaham tentang pekerjaan rumah tangga tidak bisa hidup bersama dengan harmonis.",
"Dalam hubungan yang sehat, pasangan tidak harus selalu berbicara setiap waktu untuk merasa terhubung.",
"Perasaan romantis bisa hilang seiring waktu, tetapi komitmen lebih penting dalam menjaga hubungan.",
"Teman yang terlalu bergantung pada kita akan merusak hubungan persahabatan.",
"Persahabatan tidak dapat bertahan jika tidak ada keseimbangan dalam memberikan dan menerima.",
"Teman sejati adalah mereka yang tidak hanya mendukung kita di waktu baik, tetapi juga saat kita berada di titik terendah.",
  "Berbicara tentang teman di belakang mereka adalah hal yang wajar, asalkan tidak menyakiti mereka.",
"Teman lama lebih berharga daripada teman baru, meskipun kita sudah tidak berkomunikasi sering.",
"Teman yang tidak mendukung impian kita seharusnya dihindari.",
"Perbedaan pandangan politik atau agama seharusnya bisa diterima dalam persahabatan.",
"Teman yang selalu memberi saran tanpa diminta justru bisa menjadi penghalang dalam persahabatan.",
"Menjaga hubungan persahabatan dengan pasangan romantis lebih sulit daripada menjaga hubungan dengan teman.",
"Teman yang terlalu sering meminta bantuan tanpa memberi balasan akan membuat hubungan terasa tidak adil.",
"Sering berkomunikasi dengan teman melalui media sosial mengurangi kualitas persahabatan.",
"Teman yang sering mengkritik kita, bahkan jika itu demi kebaikan, sebenarnya tidak peduli.",
"Kita seharusnya memilih teman berdasarkan kesamaan nilai, bukan hanya karena kesenangan bersama.",
"Teman yang tidak pernah mengakui kesalahan mereka sulit untuk dipertahankan sebagai teman.",
"Teman yang tidak bisa menerima kegagalan kita bukan teman sejati.",
"Jika persahabatan tidak menguntungkan, lebih baik mengakhiri hubungan tersebut.",
"Teman harus selalu memberi ruang untuk kebebasan pribadi kita, bahkan jika itu berarti mereka merasa ditinggalkan.",
"Teman seharusnya lebih jujur tentang perasaan mereka, bahkan jika itu bisa menyakiti kita.",
"Teman yang terus-menerus meminta maaf tanpa perubahan nyata tidak seharusnya diberi kesempatan kedua.",
"Teman yang memiliki pasangan yang tidak kita sukai bisa menempatkan kita dalam posisi sulit.",
"Tidak ada yang salah dengan mengakhiri pertemanan jika kita merasa tidak lagi berkembang.",
"Teman yang terlalu cemburu dengan pencapaian kita cenderung merusak hubungan.",
"Tidak perlu berbagi segala hal dengan teman, karena itu bisa merusak privasi kita.",
"Teman yang memiliki masalah dengan kepercayaan diri sering kali menarik kita ke dalam drama mereka.",
"Terkadang, kita harus mendahulukan keluarga daripada teman dalam keputusan besar hidup kita.",
"Dalam pertemanan, selalu ada pihak yang lebih memberi dan pihak yang lebih menerima.",
"Berbicara tentang teman di media sosial bisa mengurangi kedalaman hubungan kita dengan mereka.",
"Teman yang selalu berbicara buruk tentang orang lain akan cepat berbicara buruk tentang kita juga.",
"Teman yang merasa lebih superior dari kita tidak pernah bisa menjadi teman sejati.",
"Memutuskan pertemanan karena perbedaan gaya hidup atau prioritas hidup adalah hal yang sah.",
"Perbedaan status sosial seharusnya tidak menghalangi persahabatan.",
"Teman yang terlalu banyak mengeluh bisa merusak suasana hati kita.",
"Mencampurkan teman dengan hubungan romantis sering kali mengarah pada konflik.",
"Persahabatan jangka panjang sering kali berakhir karena salah satu pihak berubah terlalu banyak.",
"Teman yang tidak bisa menghargai waktu kita sebenarnya tidak peduli pada kita.",
"Kita seharusnya tidak mengorbankan prinsip kita demi menjaga persahabatan.",
"Teman yang membuat kita merasa kecil hati atau tidak dihargai tidak layak dipertahankan.",
"Menyimpan rahasia dari teman, bahkan jika itu untuk melindungi mereka, adalah hal yang bisa diterima.",
"Persahabatan yang berbasis pada ketertarikan fisik lebih rentan rusak daripada persahabatan yang tulus.",
"Teman yang jarang menunjukkan empati sebenarnya hanya berpura-pura peduli.",
"Mengambil keputusan besar hidup tanpa melibatkan teman terkadang bisa menjadi pilihan yang lebih baik.",
"Teman yang terlalu banyak menghakimi keputusan kita sebenarnya tidak mendukung kita.",
"Persahabatan sering kali lebih menyakitkan daripada hubungan romantis.",
"Menghindari konflik dengan teman sering kali membuat kita tidak jujur terhadap diri sendiri.",
"Tidak ada teman yang sempurna, dan kita seharusnya menerima kekurangan mereka.",
"Terkadang, lebih baik membatasi waktu yang kita habiskan dengan teman yang terlalu toxic.",
"Teman yang tidak bisa melihat kelebihan kita tanpa merasa iri tidak layak menjadi teman dekat.",
"Teman seharusnya memberi kita ruang untuk tumbuh, bahkan jika itu berarti kita berubah menjadi seseorang yang berbeda.",
"Memaafkan teman yang telah mengkhianati kita adalah pilihan yang sulit, tetapi kadang perlu dilakukan untuk kedamaian batin.",
"Persahabatan antara pria dan wanita hampir selalu berakhir dengan perasaan romantis salah satu pihak.",
"Teman sejati adalah mereka yang selalu mendukung, bahkan ketika kita salah.",
"Teman yang terlalu sering mengkritik kita sebenarnya tidak peduli pada kita.",
"Persahabatan tidak dapat bertahan jika salah satu teman merasa iri atau cemburu.",
"Tidak ada yang salah dengan memutuskan pertemanan yang sudah tidak mendatangkan kebahagiaan lagi.",
"Teman yang tidak mendukung impian kita seharusnya dijauhi.",
"Teman yang sering membicarakan orang lain di belakang mereka cenderung akan membicarakan kita juga.",
"Terkadang lebih baik mengorbankan hubungan persahabatan demi pertumbuhan pribadi.",
"Teman yang hanya menghubungi kita saat mereka membutuhkan sesuatu bukan teman sejati.",
"Teman lama lebih berharga daripada teman baru, meskipun kita sudah lama tidak berkomunikasi.",
"Sering berbicara tentang kehidupan pribadi kita dengan teman dapat merusak privasi kita.",
"Tidak ada yang salah dengan memutuskan hubungan dengan teman yang tidak bisa menerima perubahan kita.",
"Persahabatan yang tidak saling mendukung dalam hal karier atau ambisi akan membuat hubungan itu cepat berakhir.",
"Jika kita merasa lebih baik tanpa seseorang dalam hidup kita, seharusnya kita berhenti berusaha mempertahankan pertemanan tersebut.",
"Teman yang tidak pernah mengakui kesalahan mereka seharusnya dihindari.",
"Persahabatan hanya bisa bertahan jika ada keseimbangan antara memberi dan menerima.",
"Teman yang memiliki pasangan yang tidak kita sukai sering kali membuat hubungan kita menjadi canggung.",
"Mengabaikan perasaan kita untuk menjaga pertemanan bukanlah tindakan yang sehat.",
"Teman yang menganggap kita sebagai pesaing, bukan sekadar teman, akan membawa perasaan tidak nyaman.",
"Menyimpan rahasia dari teman seharusnya tidak merusak hubungan persahabatan.",
"Teman yang terlalu cemburu akan pencapaian kita lebih merusak daripada teman yang mendukung kita.",
"Persahabatan tidak bisa bertahan jika ada ketidakjujuran antara teman.",
"Jika pertemanan selalu membuat kita merasa tertekan, lebih baik menjauhi mereka.",
"Menjaga hubungan persahabatan dengan seseorang yang tidak sepaham dengan kita justru membuat hubungan tersebut toksik.",
"Teman yang tidak peduli dengan kesehatan atau kesejahteraan kita seharusnya tidak dipertahankan.",
"Terkadang, kita harus memberi tahu teman jika mereka melakukan sesuatu yang menyakiti kita, bahkan jika itu tidak nyaman.",
"Teman yang tidak mau berkembang bersama kita adalah teman yang tidak layak dipertahankan.",
"Tidak ada yang salah dengan berhenti berhubungan dengan teman yang toxic, meskipun itu sudah bertahun-tahun.",
"Jika teman kita tidak mengerti keputusan hidup kita, kita seharusnya tidak merasa terbebani untuk menjelaskan terlalu banyak.",
"Persahabatan bisa berakhir dengan mudah jika salah satu teman menjadi terlalu bergantung pada yang lain.",
"Teman yang selalu merasa superior cenderung tidak bisa menerima kita apa adanya.",
"Terkadang, lebih baik memilih untuk tidak berbicara dengan teman daripada mengatakan sesuatu yang bisa menyakiti perasaan mereka.",
"Terkadang, kita harus bermain 'keras untuk mendapatkan' agar orang tertarik pada kita.",
"Tidak ada yang salah dengan menggunakan kata-kata manis atau pujian untuk mendekati seseorang, meskipun itu tidak sepenuhnya tulus.",
"Jika seseorang tidak tertarik pada kita, kita harus berusaha lebih keras untuk menarik perhatian mereka.",
"Jika seseorang menolak pendekatan kita, itu bukan akhir dari dunia—kita seharusnya mencoba lagi dengan cara yang berbeda.",
  "Menyembunyikan niat kita saat mendekati seseorang sering kali diperlukan untuk membangun hubungan.",
"Menggunakan media sosial untuk mendekati seseorang bisa lebih efektif daripada bertemu langsung.",
"Pendekatan yang terlalu agresif bisa diterima selama kita merasa yakin itu yang diinginkan pihak lain.",
"Membuat orang lain cemburu bisa menjadi cara yang sah untuk mendekati mereka.",
"Jangan pernah mengungkapkan perasaan kita kepada seseorang jika kita tahu mereka tidak akan membalasnya.",
"Menggunakan orang lain untuk mendapatkan perhatian dari orang yang kita sukai adalah hal yang wajar dalam beberapa situasi.",
"Kadang-kadang kita harus menjadi lebih 'misterius' untuk menarik perhatian seseorang.",
"Mengubah diri kita sendiri untuk menarik perhatian seseorang adalah hal yang sah, meskipun itu tidak jujur.",
"Menjaga jarak untuk membuat seseorang tertarik lebih efektif daripada menunjukkan ketertarikan secara langsung.",
"Jika seseorang tertarik pada kita, mereka akan melakukan langkah pertama—kita tidak perlu mengambil inisiatif.",
"Mencari perhatian orang yang sudah memiliki pasangan adalah hal yang tidak etis, meskipun kita merasa sangat tertarik padanya.",
"Menunjukkan ketertarikan terlalu cepat sering kali bisa membuat orang lari.",
"Kita tidak perlu menjadi diri sendiri sepenuhnya ketika sedang mendekati seseorang untuk membuat mereka tertarik.",
"Membuat diri kita terlihat sibuk atau tidak tertarik sering kali bisa membuat orang lebih tertarik.",
"Terkadang, pendekatan yang halus dan tidak langsung lebih efektif daripada yang terlalu terbuka.",
"Seseorang yang benar-benar tertarik pada kita tidak akan bermain-main dengan perasaan kita.",
"Menggunakan humor atau candaan untuk menarik perhatian seseorang adalah cara yang sah dan efektif.",
"Mengubah penampilan fisik kita untuk menarik perhatian seseorang adalah hal yang wajar dan sah.",
"Jika kita sudah tahu bahwa seseorang tidak tertarik pada kita, kita seharusnya tetap mencoba mendekatinya.",
"Menggunakan keahlian atau hobi kita untuk mendekati seseorang adalah taktik yang sah.",
"Terkadang, orang yang kita dekati tidak menyadari ketertarikan kita sampai kita secara langsung menyatakannya.",
"Menjadi lebih tertutup atau misterius daripada terlalu terbuka adalah cara yang lebih baik untuk menarik perhatian.",
"Seseorang yang suka bermain-main dengan perasaan kita seharusnya diberi kesempatan untuk menunjukkan niat mereka yang sebenarnya.",
"Jangan terlalu cepat membuka diri kepada seseorang yang baru kita kenal, karena itu bisa membuat mereka merasa tidak nyaman.",
"Orang cenderung tertarik pada orang yang tidak terlalu membutuhkan perhatian mereka.",
"Jika kita merasa tertarik pada seseorang, kita seharusnya langsung mengungkapkan perasaan kita tanpa menunggu terlalu lama.",
"Menggunakan pengaruh teman-teman untuk mendekati seseorang yang kita suka adalah taktik yang sah.",
"Seseorang yang tidak bisa menunjukkan ketertarikan secara langsung sebenarnya tidak tertarik pada kita.",
"Menggunakan status sosial atau popularitas untuk menarik perhatian seseorang adalah hal yang sah, meskipun kontroversial.",
"Mencari tahu informasi pribadi tentang seseorang untuk mendekati mereka lebih cepat adalah hal yang bisa diterima dalam situasi tertentu.",
"Kadang-kadang, pendekatan yang terlalu lembut atau halus malah membuat seseorang tidak menyadari bahwa kita tertarik padanya.",
"Mengabaikan seseorang untuk sementara waktu bisa meningkatkan ketertarikan mereka kepada kita.",
"Jika seseorang tidak memberikan tanda ketertarikan, kita harus menghormati keputusan mereka dan berhenti mencoba mendekati.",
"Pendekatan yang terlalu langsung dan terbuka lebih jarang berhasil daripada yang lebih subtil.",
"Menunjukkan minat pada hal-hal yang disukai oleh orang yang kita sukai bisa membuat kita lebih menarik di mata mereka.",
"Orang cenderung lebih tertarik pada seseorang yang tampak sulit didapat atau sulit didekati.",
"Menggunakan kata-kata manis atau romantis pada awalnya bisa membuat hubungan berkembang lebih cepat.",
"Jika seseorang benar-benar tertarik pada kita, mereka akan menunjukkan ketertarikan tanpa perlu kita dorong.",
"Menunjukkan perhatian berlebihan pada seseorang yang kita sukai bisa membuat mereka merasa tidak nyaman.",
"Terkadang, menunjukkan sedikit kecemburuan atau ketidaktertarikan bisa membuat seseorang lebih tertarik.",
"Tidak perlu terlalu banyak usaha untuk mendekati seseorang—perasaan yang tulus lebih penting daripada tindakan kita.",
"Menggunakan taktik yang disengaja untuk membuat orang tertarik pada kita sering kali berhasil meskipun tidak etis.",
"Kita seharusnya tidak membuang waktu untuk mendekati seseorang yang tidak menunjukkan tanda-tanda ketertarikan yang jelas.",
"Mengungkapkan perasaan kita tanpa persiapan sering kali bisa membuat kita terlihat lemah dan membutuhkan perhatian.",
"Terkadang, kita harus membuat seseorang merasa bahwa mereka kehilangan kesempatan untuk mendekati kita agar mereka tertarik.",
"Jangan pernah mendekati seseorang hanya untuk mendapatkan keuntungan pribadi—itu merusak hubungan yang sehat.",
"Hukum aborsi seharusnya dibolehkan di seluruh dunia, tanpa terkecuali.",
"Kekayaan yang sangat besar seharusnya dikenakan pajak lebih tinggi untuk mengurangi ketimpangan sosial.",
"Penggunaan media sosial lebih banyak memberikan dampak negatif daripada positif terhadap kesehatan mental.",
"Pendidikan tinggi seharusnya gratis untuk semua orang agar tercipta pemerataan kesempatan.",
"Denda atau hukuman untuk tindakan kriminal seharusnya berdasarkan pada status sosial dan kemampuan finansial seseorang.",
"Seharusnya ada pembatasan untuk jumlah anak yang dimiliki oleh satu keluarga demi keberlanjutan lingkungan.",
"Semua agama memiliki kebenaran yang sama, dan kita seharusnya tidak membedakan satu dengan yang lainnya.",
"Mengontrol populasi melalui kebijakan pemerintah lebih penting daripada kebebasan individu dalam memilih jumlah anak.",
"Rasisme dan diskriminasi berdasarkan ras seharusnya dikenakan hukuman yang lebih keras daripada tindak kriminal lainnya.",
"Semua pekerjaan, tidak peduli jenisnya, seharusnya dibayar dengan jumlah yang sama.",
"Pembatasan kebebasan berbicara di media sosial untuk mencegah ujaran kebencian adalah hal yang sah.",
"Gaya hidup hedonistik dan konsumerisme adalah penyebab utama kerusakan lingkungan global.",
"Hukum pernikahan seharusnya mengizinkan pernikahan antara lebih dari dua orang (poligami atau poliandri).",
"Hukuman mati harus tetap diterapkan di negara-negara yang memiliki tingkat kriminalitas tinggi.",
"Menyembunyikan informasi penting untuk keuntungan pribadi seharusnya dihukum dengan penjara seumur hidup.",
"Hak atas kebebasan berpakaian harus sepenuhnya dibiarkan, tanpa batasan norma sosial atau agama.",
"Hak-hak transpuan dan transman seharusnya diakui di seluruh dunia, bahkan jika bertentangan dengan norma budaya setempat.",
"Pemerintah seharusnya bertanggung jawab dalam memerangi perubahan iklim, bahkan jika itu berarti membatasi kebebasan ekonomi.",
"Semua negara seharusnya mengizinkan pernikahan sesama jenis tanpa syarat atau pengecualian.",
"Perlakuan terhadap hewan di industri makanan dan kosmetik seharusnya dilarang demi etika dan kesejahteraan mereka.",
"Pendidikan agama di sekolah umum seharusnya dihapuskan demi kebebasan beragama.",
"Pemerintah harus memberikan subsidi untuk setiap orang yang memutuskan untuk memiliki anak lebih dari dua.",
"Pemerintah seharusnya memaksa warga untuk menjalani vaksinasi terhadap penyakit menular, meskipun itu bertentangan dengan kebebasan individu.",
"Kebebasan pers seharusnya dibatasi untuk mencegah penyebaran informasi yang tidak benar atau hoaks.",
"Tidak ada alasan yang sah untuk menentang hak reproduksi wanita, termasuk dalam kasus kehamilan yang tidak diinginkan.",
"Semua jenis narkoba seharusnya dilegalkan dan diatur oleh pemerintah agar bisa mengurangi kejahatan terkait narkoba.",
"Pemanasan global adalah ancaman yang lebih besar daripada ancaman terorisme atau perang dunia.",
"Hukum yang mengatur kebebasan berbicara di media sosial seharusnya lebih ketat untuk mengurangi penyebaran kebencian dan disinformasi.",
"Semua agama harus dilarang di tempat kerja atau di lingkungan profesional untuk menjaga objektivitas dan inklusivitas.",
"Penggunaan teknologi canggih untuk mengendalikan populasi, seperti pemantauan AI, seharusnya diterima demi keamanan nasional.",
"Semua bentuk kekerasan, baik fisik maupun verbal, seharusnya dihukum dengan hukuman yang setimpal, tanpa toleransi.",
"Kebijakan imigrasi harus lebih terbuka dan tidak membatasi hak para imigran untuk tinggal atau bekerja di negara lain.",
"Pemerintah seharusnya memberikan uang saku kepada semua orang yang membutuhkan, tanpa syarat, untuk mengurangi kemiskinan.",
"Teknologi canggih seperti AI dan robot harus lebih dikendalikan agar tidak menggantikan pekerjaan manusia secara massal.",
"Pembatasan hak pribadi untuk tujuan keamanan nasional (misalnya, pemantauan) seharusnya diperbolehkan.",
"Hukuman penjara seharusnya hanya diterapkan untuk pelanggaran kriminal berat, dan pelanggaran ringan harus mendapatkan hukuman alternatif.",
"Menuntut hak cipta atas karya seni dan ide kreatif harus dihapuskan untuk mendukung penyebaran informasi dan kreativitas bebas.",
"Setiap orang seharusnya memiliki hak untuk memilih atau menolak identitas gender mereka, tanpa adanya tekanan sosial.",
"Penerapan sistem kasta dalam masyarakat modern adalah sesuatu yang tidak bisa dihindari dan tetap ada dalam setiap budaya.",
"Pembatasan jumlah kendaraan pribadi untuk mengurangi emisi seharusnya dilakukan oleh semua negara, meskipun itu membatasi kebebasan individu.",
"Penggunaan uang publik untuk mendanai agama tertentu harus dihentikan karena melanggar prinsip sekularisme.",
"Pemerintah harus memiliki kontrol penuh atas internet untuk mengurangi ancaman teroris dan penyebaran konten berbahaya.",
"Menjadi vegetarian atau vegan adalah satu-satunya cara untuk membantu menyelamatkan planet ini.",
"Anak-anak seharusnya tidak dipaksa untuk mengikuti agama tertentu oleh orang tua mereka.",
"Pencurian kecil, seperti pencurian makanan untuk bertahan hidup, seharusnya tidak dihukum.",
"Pendekatan militer terhadap terorisme seharusnya lebih ditekankan daripada diplomasi.",
"Penggunaan teknologi dalam dunia pendidikan seharusnya dipercepat meskipun itu berarti menggantikan beberapa aspek tradisional.",
"Sebagian besar negara seharusnya melegalkan euthanasia bagi mereka yang menderita penyakit terminal.",
"Kualitas hidup seharusnya diutamakan daripada panjang umur, dan euthanasia seharusnya diperbolehkan atas permintaan individu.",
"Negara harus memiliki kontrol ketat atas media untuk menjaga moral masyarakat dan menghentikan penyebaran informasi yang merusak.",
"Seks harus menjadi bagian dari hubungan yang penuh komitmen dan kepercayaan.",
"Pendidikan seks di sekolah harus diberikan sejak usia dini untuk menghindari kesalahpahaman.",
"Keputusan untuk berhubungan seksual seharusnya selalu dilandasi dengan persetujuan dari kedua belah pihak.",
"Menjaga kesehatan seksual harus menjadi prioritas dalam hubungan jangka panjang.",
"Seksualitas seseorang adalah hak pribadi yang tidak perlu dihakimi oleh orang lain.",
"Seks yang dilakukan di luar ikatan pernikahan tidak selalu berdampak buruk bagi individu.",
"Kontrasepsi seharusnya menjadi hak semua orang yang aktif secara seksual untuk mencegah kehamilan yang tidak diinginkan.",
"Pornografi dapat memengaruhi persepsi individu tentang seks dan hubungan intim.",
"Adanya komunikasi terbuka mengenai preferensi seksual penting untuk menjaga keharmonisan dalam hubungan.",
"Seksualitas bukan hanya soal aktivitas fisik, tetapi juga berkaitan dengan kesehatan mental dan emosional.",
"Seksualitas seseorang bisa berubah sepanjang hidup mereka, dan itu adalah hal yang alami.",
"Kehamilan di luar pernikahan seharusnya tidak menjadi stigma sosial.",
"Masyarakat harus lebih terbuka dalam membicarakan kesehatan seksual untuk mengurangi tabungan.",
"Seksualitas harus dieksplorasi dengan penuh rasa hormat terhadap diri sendiri dan pasangan.",
"Kegiatan seksual dalam pernikahan seharusnya dilakukan atas dasar saling pengertian dan bukan kewajiban.",
"Tindakan pemaksaan seksual adalah pelanggaran hak asasi manusia yang sangat serius.",
"Kebebasan dalam mengekspresikan seksualitas seharusnya dihormati selama tidak merugikan orang lain.",
"Seks yang tidak aman dapat menimbulkan risiko kesehatan yang besar bagi individu dan pasangan.",
"Masalah dalam kehidupan seksual seharusnya dapat dibicarakan dengan terbuka kepada profesional kesehatan.",
"Setiap orang berhak untuk membuat keputusan pribadi terkait dengan kehidupan seksual mereka tanpa pengaruh dari masyarakat.",
"Aktivitas seksual tidak harus selalu berhubungan dengan orgasme untuk menjadi pengalaman yang memuaskan.",
"Seksualitas harus dipahami dalam konteks budaya dan sosial yang beragam, tanpa memaksakan satu pandangan tunggal.",
"Identitas gender yang tidak sesuai dengan jenis kelamin biologis seharusnya diterima dalam hubungan seksual yang sehat.",
"Keterbukaan pasangan dalam berbicara tentang seksualitas dapat meningkatkan kualitas hubungan.",
"Menghormati batasan seksual pasangan adalah tanda dari hubungan yang sehat dan saling menghargai.",
"Setiap individu memiliki hak untuk memilih jenis kontrasepsi yang sesuai dengan kebutuhan mereka.",
"Seksualitas seharusnya tidak menjadi alat untuk mengontrol atau memanipulasi orang lain.",
"Pendidikan seks yang baik dapat membantu mencegah masalah kesehatan seksual dan penyebaran penyakit menular seksual.",
"Kehidupan seksual seharusnya tidak dijadikan alasan untuk merendahkan atau mengecilkan martabat seseorang.",
"Pemahaman tentang seksualitas yang sehat harus diajarkan di rumah, sekolah, dan masyarakat untuk menciptakan lingkungan yang aman dan mendukung.",
"Menghabiskan waktu di media sosial lebih banyak memberikan manfaat daripada dampak negatif.",
"Sarapan adalah waktu makan yang paling penting dalam sehari.",
"Makan malam terlalu larut dapat merusak pola tidur dan kesehatan.",
"Mempunyai rutinitas pagi yang teratur dapat meningkatkan produktivitas sepanjang hari.",
"Belanja online lebih praktis daripada berbelanja langsung ke toko.",
"Tidur seharusnya lebih diutamakan daripada bekerja larut malam.",
"Mengatur waktu dengan aplikasi atau to-do list sangat membantu dalam menyelesaikan pekerjaan.",
"Menghabiskan waktu berkualitas dengan keluarga lebih penting daripada mengejar karier.",
"Menyisihkan waktu untuk hobi bisa mengurangi stres.",
"Menonton acara TV lebih menyenangkan daripada menonton film.",
"Memiliki waktu sendiri setiap hari penting untuk menjaga kesehatan mental.",
"Mengikuti tren fesyen seharusnya tidak mempengaruhi cara berpakaian sehari-hari.",
"Memasak makanan sendiri lebih sehat daripada makan di luar.",
"Menggunakan transportasi umum lebih ramah lingkungan dibandingkan dengan menggunakan kendaraan pribadi.",
"Pekerjaan freelance memberikan kebebasan lebih dibandingkan dengan pekerjaan kantoran.",
"Makan terlalu banyak camilan sepanjang hari dapat memengaruhi kesehatan.",
"Menghabiskan waktu di luar ruangan setiap hari baik untuk kesehatan fisik dan mental.",
"Makan bersama keluarga adalah kebiasaan yang seharusnya tetap dijaga.",
"Tidur cukup lebih penting daripada berolahraga setiap hari.",
"Menggunakan teknologi lebih sering dapat menyebabkan ketergantungan digital.",
"Berbelanja barang-barang diskon tidak selalu berarti lebih hemat.",
"Mengatur keuangan dengan aplikasi lebih efektif dibandingkan mencatat manual.",
"Belajar sesuatu yang baru setiap hari dapat meningkatkan kualitas hidup.",
"Memiliki jadwal tidur yang konsisten lebih baik daripada tidur dengan durasi lama tanpa pola.",
"Menonton film dengan subtitle lebih menguntungkan dalam memahami cerita daripada hanya mendengarkan.",
"Menjaga kebersihan rumah merupakan tanggung jawab bersama bagi semua anggota keluarga.",
"Pekerjaan rumah tangga seharusnya dilakukan secara adil antara pasangan.",
"Menyisihkan waktu untuk berolahraga walau hanya 15 menit setiap hari sudah cukup efektif.",
"Keterampilan memasak adalah keahlian penting yang harus dimiliki setiap orang.",
"Menghabiskan waktu bersama teman-teman lebih menyenangkan daripada sendirian di rumah.",
"Mengurangi penggunaan plastik dapat berkontribusi pada pelestarian lingkungan.",
"Mengurangi konsumsi makanan cepat saji seharusnya menjadi kebiasaan sehat sehari-hari.",
"Memiliki waktu tanpa gadget sangat bermanfaat untuk menjaga hubungan sosial yang lebih sehat.",
"Memberikan tips atau saran kepada orang lain lebih bermanfaat daripada hanya berbicara tentang masalah.",
"Mengikuti acara atau kegiatan komunitas di lingkungan sekitar dapat mempererat hubungan sosial.",
"Menjaga kebersihan diri dan lingkungan rumah secara teratur dapat membuat suasana hati lebih baik.",
"Memulai hari dengan olahraga ringan memberikan energi yang cukup untuk aktivitas sehari-hari.",
"Menghemat energi di rumah lebih penting daripada mengutamakan kenyamanan.",
"Mengikuti perkembangan berita sehari-hari penting untuk mengetahui keadaan dunia.",
"Menggunakan waktu untuk merencanakan hari lebih efektif daripada hanya mengikuti alur harian tanpa rencana.",
"Cara kita berpakaian mencerminkan siapa diri kita sebenarnya.",
"Penampilan fisik sering kali lebih diprioritaskan daripada kepribadian dalam penilaian pertama.",
"Orang sering menilai kita berdasarkan pekerjaan yang kita pilih.",
"Apa yang kita unggah di media sosial bisa memberikan gambaran tentang karakter kita.",
"Cara kita berinteraksi dengan orang lain memberikan gambaran tentang sejauh mana kita peduli dengan mereka.",
"Orang lebih cenderung menilai kita berdasarkan kesuksesan material daripada kebahagiaan pribadi.",
"Kepercayaan diri yang ditampilkan sering kali mempengaruhi bagaimana orang melihat kita.",
"Orang akan menilai kita berdasarkan latar belakang keluarga atau tempat asal kita.",
"Tindakan kita berbicara lebih keras daripada kata-kata dalam membentuk persepsi orang terhadap kita.",
"Keterbukaan kita dalam berbagi kehidupan pribadi dapat mempengaruhi bagaimana orang melihat kita.",
"Orang cenderung menilai kita dari cara kita berbicara atau berkomunikasi.",
"Penilaian orang terhadap kita sering kali dipengaruhi oleh stereotip dan prasangka.",
"Apakah kita berperilaku ramah atau tertutup akan mempengaruhi kesan orang terhadap kita.",
"Keputusan kita untuk berbagi pendapat dapat mengubah cara orang memandang kita.",
"Orang lebih sering menilai kita berdasarkan bagaimana kita menyelesaikan masalah daripada dari awalnya.",
"Bagaimana kita mengelola waktu dan prioritas hidup mempengaruhi cara orang melihat kita.",
"Keberhasilan kita dalam hal karier lebih sering dilihat sebagai indikator kemampuan kita daripada usaha pribadi.",
"Tindakan kebaikan atau kemurahan hati kita dapat membentuk citra positif di mata orang lain.",
"Cara kita mengelola emosi, terutama dalam situasi stres, menunjukkan karakter sejati kita.",
  "Cara kita memilih untuk menghabiskan waktu luang sering memberi petunjuk tentang minat dan kepribadian kita.",
"Stereotip sosial seringkali membentuk bagaimana orang menilai kita sebelum mereka benar-benar mengenal kita.",
"Orang cenderung menilai kita lebih baik jika kita memiliki selera humor yang baik.",
"Apa yang kita lakukan di ruang pribadi sering kali mengungkapkan lebih banyak tentang kita daripada apa yang kita lakukan di ruang publik.",
"Bagaimana kita memperlakukan orang yang tidak bisa memberi manfaat langsung pada kita berpengaruh pada cara orang melihat kita.",
"Orang sering menilai kita berdasarkan apakah kita beradaptasi dengan norma sosial atau tidak.",
"Bagaimana kita memandang kegagalan sering memberi gambaran tentang ketahanan mental kita.",
"Orang lebih cenderung menghargai kita jika kita terlihat memiliki kontrol atas hidup kita.",
"Memiliki pendapat yang berbeda dalam kelompok sering mengubah cara orang melihat kita.",
"Orang sering menilai kita berdasarkan rasa tanggung jawab yang kita tunjukkan terhadap orang lain.",
"Menghindari konfrontasi atau selalu menghindari masalah bisa membuat orang menganggap kita sebagai orang yang lemah atau tidak tegas.",
"Cara kita merespons kritik sering menentukan bagaimana orang melihat kemampuan kita.",
"Orang sering menilai kita berdasarkan bagaimana kita memperlakukan orang yang lebih rendah posisi sosialnya.",
"Apakah kita cepat marah atau sabar sering kali menjadi faktor dalam bagaimana orang melihat kita.",
"Orang akan menilai kita dari cara kita memperlakukan orang asing atau orang yang tidak kita kenal dengan baik.",
"Orang yang terbuka tentang kelemahan mereka sering dianggap lebih jujur dan autentik.",
"Apakah kita lebih fokus pada pencapaian pribadi atau kepentingan bersama dapat mempengaruhi persepsi orang terhadap kita.",
"Keterlibatan kita dalam kegiatan sosial dan kemanusiaan sering memberi kesan positif tentang kita.",
"Orang sering menilai kita berdasarkan bagaimana kita menangani kegagalan atau kesulitan dalam hidup.",
"Bagaimana kita memperlakukan hewan atau alam sering mencerminkan nilai-nilai moral kita di mata orang lain.",
"Pilihan kita dalam bersosialisasi, apakah kita lebih suka bergaul dengan banyak orang atau lebih memilih sedikit teman dekat, sering dipandang sebagai indikasi karakter kita.",
"Orang sering menilai kita dari seberapa besar kita berbagi kebahagiaan dengan orang lain, bukan hanya pencapaian pribadi.",
"Memiliki pendirian yang kuat dapat membuat orang melihat kita sebagai seseorang yang tegas, namun juga bisa menimbulkan kesan keras kepala.",
"Cara kita menunjukkan empati terhadap orang yang sedang dalam kesulitan sering mempengaruhi bagaimana orang melihat kebaikan hati kita.",
"Apakah kita lebih sering berbicara atau mendengarkan bisa memberikan gambaran tentang seberapa besar kita menghargai orang lain.",
"Orang lebih cenderung menghargai kita jika kita bisa menempatkan diri dengan baik dalam situasi sosial yang berbeda.",
"Memiliki kehidupan yang sangat terorganisir atau teratur bisa membuat orang melihat kita sebagai seseorang yang disiplin, namun juga bisa dianggap kaku.",
"Cara kita beradaptasi dengan perubahan hidup atau keadaan baru sering menjadi penilaian utama orang terhadap ketahanan pribadi kita.",
"Orang sering menilai kita dari seberapa baik kita menjaga hubungan dengan keluarga dekat.",
"Keinginan kita untuk belajar hal-hal baru dapat memberi kesan bahwa kita adalah individu yang berkembang dan terbuka.",
"Cara kita mengatasi perbedaan pendapat dalam diskusi sering kali mencerminkan kedewasaan emosional kita di mata orang lain.",
"Bekerja di perusahaan besar lebih menguntungkan dibandingkan bekerja di startup kecil.",
"Karyawan seharusnya diberi kebebasan untuk bekerja dari mana saja tanpa adanya batasan.",
"Gaji yang tinggi tidak selalu berhubungan dengan kepuasan kerja.",
"Pekerjaan dengan jadwal fleksibel lebih produktif daripada pekerjaan dengan jam kerja tetap.",
"Karyawan tidak seharusnya menghabiskan waktu di luar jam kerja untuk memikirkan pekerjaan.",
"Keberhasilan dalam pekerjaan lebih banyak bergantung pada jaringan dan hubungan daripada kemampuan individu.",
"Perusahaan harus memberikan lebih banyak peluang untuk pengembangan karier bagi karyawan mereka.",
"Pekerjaan yang penuh tantangan lebih memuaskan dibandingkan pekerjaan yang hanya rutinitas sehari-hari.",
"Ada lebih banyak kebahagiaan dalam pekerjaan yang berbasis kreativitas daripada pekerjaan yang monoton.",
"Pekerjaan yang dilakukan dengan passion lebih menguntungkan dalam jangka panjang.",
"Sistem kerja 4 hari dalam seminggu lebih efisien daripada sistem kerja 5 hari.",
"Karyawan seharusnya lebih dihargai dengan memberi bonus berdasarkan pencapaian, bukan hanya gaji bulanan.",
"Bekerja di sektor publik seringkali menawarkan stabilitas yang lebih baik dibandingkan sektor swasta.",
"Bekerja dengan rekan satu tim lebih menguntungkan daripada bekerja sendirian.",
"Perusahaan seharusnya lebih memperhatikan kesejahteraan mental karyawan.",
"Pengalaman kerja lebih berharga daripada gelar pendidikan formal dalam mencari pekerjaan.",
"Profesionalisme di tempat kerja seringkali dibatasi oleh norma dan budaya perusahaan.",
"Pekerja lepas (freelancer) lebih memiliki kebebasan dibandingkan karyawan tetap.",
"Menjadi bos di perusahaan lebih menarik dibandingkan menjadi karyawan biasa.",
"Pekerjaan remote seharusnya menjadi pilihan utama bagi pekerja di bidang kreatif.",
"Adanya kejelasan tujuan dan peran di tempat kerja meningkatkan produktivitas.",
"Pekerja yang lebih tua seharusnya mendapatkan kesempatan yang sama dengan pekerja muda dalam pekerjaan yang sama.",
"Pekerjaan yang menawarkan kesempatan untuk travel membuatnya lebih menarik.",
"Penggunaan teknologi di tempat kerja mempermudah pekerjaan, namun juga menciptakan ketergantungan.",
"Menjaga keseimbangan antara kehidupan pribadi dan pekerjaan seharusnya menjadi prioritas bagi semua orang.",
"Bekerja di industri kreatif lebih penuh tekanan dibandingkan pekerjaan administratif.",
"Keberhasilan dalam pekerjaan tidak hanya ditentukan oleh hasil akhir, tetapi juga oleh proses yang dijalani.",
"Semua pekerjaan, baik itu pekerjaan tangan atau pekerjaan intelektual, seharusnya mendapatkan penghargaan yang sama.",
"Perusahaan seharusnya memperkenalkan lebih banyak program mentoring untuk meningkatkan kemampuan karyawan.",
"Pekerjaan yang memberikan peluang untuk berinovasi lebih menarik daripada pekerjaan yang hanya mengikuti prosedur yang ada.",
"Menjalin hubungan tanpa status memberikan kebebasan untuk lebih fokus pada diri sendiri.",
"Hubungan tanpa status sering kali membingungkan dan menyakitkan karena ekspektasi yang tidak jelas.",
"Dalam hubungan tanpa status, kedua belah pihak harus sepakat tentang apa yang mereka inginkan untuk menghindari perasaan terluka.",
"Tidak ada komitmen yang jelas dalam hubungan tanpa status membuatnya lebih mudah berakhir kapan saja.",
"Hubungan tanpa status dapat mengarah pada kebingungan tentang perasaan dan keinginan masing-masing individu.",
"Meskipun tidak ada status, rasa saling pengertian dan komunikasi tetap penting untuk menjaga hubungan yang sehat.",
"Hubungan tanpa status bisa lebih bebas dari tekanan sosial, namun dapat membuat orang merasa kesepian dalam jangka panjang.",
"Ketidakjelasan dalam hubungan tanpa status bisa merusak persahabatan yang sebelumnya sudah terjalin.",
"Dalam hubungan tanpa status, perasaan cinta atau kasih sayang bisa berkembang tanpa terbebani oleh label atau kewajiban.",
"Beberapa orang merasa lebih aman berada dalam hubungan tanpa status, karena mereka tidak terikat pada komitmen jangka panjang.",
"Pertemanan antara pria dan wanita selalu memiliki potensi untuk berubah menjadi sesuatu yang lebih romantis.",
"Ketika satu teman mulai memiliki perasaan terhadap yang lain, pertemanan bisa menjadi canggung atau rusak.",
"Memiliki teman lawan jenis dalam hubungan romantis bisa menambah dinamika dan kepercayaan.",
"Pertemanan lawan jenis yang dekat seringkali menimbulkan kecemburuan di antara pasangan romantis.",
"Jika dua orang saling menghormati batasan, pertemanan antara pria dan wanita bisa sangat sehat dan produktif.",
"Dalam banyak kasus, pria dan wanita tidak bisa benar-benar menjadi 'hanya teman' tanpa adanya ketertarikan emosional atau fisik.",
"Perbedaan gender dalam pertemanan dapat menyebabkan kesalahpahaman yang sulit dihindari.",
"Teman lawan jenis seharusnya tidak dipandang sebagai ancaman dalam hubungan romantis, tetapi lebih sebagai sumber dukungan.",
"Ketika dua orang dari lawan jenis berteman, mereka sering kali merasa tertekan untuk menjaga jarak agar tidak dianggap lebih dari teman.",
"Pertemanan antara pria dan wanita dapat menjadi lebih kompleks ketika salah satu pihak sudah berada dalam hubungan romantis.",
"Cemburu dalam hubungan bisa menjadi tanda bahwa seseorang peduli, tetapi jika berlebihan bisa merusak kepercayaan.",
"Cemburu adalah emosi yang wajar, namun penting untuk mengelola perasaan tersebut agar tidak mengganggu dinamika hubungan.",
"Ketika seseorang merasa cemburu, itu bisa mencerminkan rasa tidak aman atau ketidakpercayaan terhadap pasangan.",
"Menjaga privasi dalam hubungan terkadang dapat menumbuhkan rasa cemburu yang tidak perlu, terutama jika tidak ada transparansi.",
"Cemburu dapat menunjukkan adanya ketergantungan emosional yang perlu diatasi untuk mencapai hubungan yang lebih sehat dan seimbang.",
"Mengungkapkan perasaan yang lebih dalam kepada seseorang yang kamu sukai bisa memperkuat hubungan, meskipun ada risiko ditolak.",
"Ketika sudah merasa nyaman dengan seseorang, mengambil langkah untuk mengenal lebih jauh dan melanjutkan hubungan ke tingkat yang lebih serius adalah hal yang wajar.",
"Berkomitmen dalam suatu hubungan seharusnya dilakukan setelah merasa benar-benar yakin dan sudah saling mengenal dengan baik.",
"Mempersiapkan diri untuk melangkah ke jenjang yang lebih serius memerlukan komunikasi yang terbuka dan kesiapan emosional dari kedua belah pihak.",
"Terkadang, mengambil langkah lebih serius dalam hubungan bisa menjadi keputusan yang tepat meskipun belum ada jaminan tentang bagaimana masa depan akan berjalan."
  
];
// Menampilkan pertanyaan secara acak
function showRandomQuestion() {
  const randomIndex = Math.floor(Math.random() * questions.length);
  const questionText = questions[randomIndex];
  document.querySelector(".question").textContent = questionText;
}

// Mengubah pertanyaan ketika tombol "NEXT CARD" ditekan
document.getElementById("next-btn").addEventListener("click", showRandomQuestion);

// Menampilkan pertanyaan pertama saat halaman dimuat
window.onload = showRandomQuestion;

