// Daftar pertanyaan
const questions = [
    "Kebebasan berbicara seharusnya tidak memiliki batas, bahkan jika itu menyinggung kelompok tertentu.",
    "Hukuman mati adalah solusi yang sah untuk kejahatan berat.",
    "Manusia seharusnya tidak mencoba memanipulasi genetik untuk menciptakan “manusia sempurna.”",
    "Perubahan iklim lebih banyak disebabkan oleh perilaku manusia daripada siklus alami bumi.",
    "Kekayaan dunia terlalu banyak terpusat di tangan segelintir orang.",
    "Perkembangan kecerdasan buatan pada akhirnya akan mengancam eksistensi manusia.",
    "Media sering kali memanipulasi opini publik untuk mendukung kepentingan tertentu.",
    "Perang terkadang diperlukan untuk menciptakan perdamaian yang abadi.",
    "Pendidikan gratis untuk semua orang adalah hak fundamental manusia.",
    "Kebijakan pembatasan kelahiran seharusnya diterapkan di negara-negara dengan populasi yang terlalu besar.",
    "Agama sering kali lebih memecah belah daripada menyatukan umat manusia.",
    "Negara kaya memiliki kewajiban moral untuk membantu negara miskin.",
    "Perbedaan budaya tidak seharusnya dijadikan alasan untuk mempertahankan tradisi yang melanggar hak asasi manusia.",
    "Hak untuk memiliki senjata api lebih banyak membawa bahaya daripada perlindungan.",
    "Penebangan hutan untuk memenuhi kebutuhan manusia tidak bisa dihindari.",
    "Orang kaya seharusnya membayar pajak lebih tinggi untuk mendukung kesejahteraan sosial.",
    "Eutanasia (hak untuk mati) adalah hak yang seharusnya dimiliki setiap manusia.",
    "Privasi individu sering kali dikorbankan secara tidak adil demi keamanan nasional.",
    "Negara seharusnya tidak ikut campur dalam keputusan reproduksi individu, termasuk aborsi.",
    "Kolonialisme modern masih berlangsung dalam bentuk kontrol ekonomi global.",
    "Perkawinan sesama jenis seharusnya diakui secara global tanpa syarat.",
    "Penggunaan hewan untuk pengujian medis dan kosmetik seharusnya dilarang sepenuhnya.",
    "Teknologi seperti kamera pengawas menciptakan dunia yang lebih aman, meskipun merusak privasi.",
    "Pendidikan agama seharusnya tidak diajarkan di sekolah-sekolah negeri.",
    "Kebebasan ekonomi sering kali menciptakan ketidakadilan yang lebih besar daripada kesejahteraan.",
    "Kehidupan di planet lain lebih mungkin ditemukan daripada keberadaan Tuhan.",
    "Setiap negara memiliki hak untuk menutup perbatasannya dari imigrasi.",
    "Kebijakan afirmasi untuk kelompok yang terpinggirkan lebih banyak merugikan daripada membantu.",
    "Teknologi cloning manusia tidak boleh dikembangkan, bahkan untuk alasan medis.",
    "Anak-anak tidak seharusnya dipaksa mengikuti tradisi budaya atau agama orang tua mereka.",
    "Keberhasilan individu lebih banyak bergantung pada faktor keberuntungan daripada kerja keras.",
    "Teknologi telah lebih banyak merugikan daripada menguntungkan umat manusia.",
    "Setiap orang berhak mendapatkan kekayaan yang tak terbatas, terlepas dari bagaimana mereka mendapatkannya.",
    "Kapitalisme adalah sistem yang lebih adil daripada sosialisme.",
    "Pemerintah seharusnya tidak memiliki hak untuk mengatur kehidupan pribadi warganya.",
    "Pendidikan formal lebih membatasi kreativitas daripada mengembangkannya.",
    "Agama seharusnya tidak lagi memiliki peran dalam kehidupan politik dan sosial.",
    "Perlindungan hak asasi manusia harus lebih diutamakan daripada keamanan nasional.",
    "Ketidaksetaraan gender adalah masalah yang lebih kompleks daripada sekadar perjuangan hak-hak perempuan.",
    "Globalisasi lebih banyak merusak budaya lokal daripada memberikan manfaat.",
    "Cinta sejati hanya bisa ditemukan setelah seseorang benar-benar merasa bahagia dengan diri sendiri.",
    "Tidak ada hubungan yang bisa bertahan tanpa pengorbanan besar dari kedua belah pihak.",
    "Perbedaan pandangan politik atau agama adalah alasan yang sah untuk mengakhiri hubungan romantis.",
    "Kepercayaan itu mudah dibangun, tetapi sangat sulit untuk dipertahankan dalam hubungan jangka panjang.",
    "Seseorang bisa mencintai lebih dari satu orang pada saat yang bersamaan tanpa itu mengurangi kualitas hubungan.",
    "Hubungan yang sehat adalah hubungan di mana kedua belah pihak memiliki kebebasan untuk mengejar impian pribadi, bahkan jika itu mengorbankan hubungan.",
    "Cemburu dalam hubungan adalah tanda cinta yang sehat, jika itu dilakukan dalam batas wajar.",
    "Ketika pasangan tidak setuju dengan keputusan besar dalam hidup, itu adalah tanda bahwa hubungan tersebut tidak dapat berkembang.",
    "Percintaan yang dimulai dari persahabatan lebih berisiko gagal dibandingkan percintaan yang dimulai dari ketertarikan fisik.",
    "Hubungan yang penuh konflik lebih bermanfaat dalam jangka panjang daripada hubungan yang selalu damai.",
    "Seringkali, lebih baik mengakhiri hubungan jika salah satu pasangan tidak bisa berkompromi.",
    "Ketika hubungan sudah terasa monoton, salah satu pasangan berhak mencari kebahagiaan di luar hubungan.",
    "Pernikahan bukanlah solusi untuk mengatasi masalah dalam hubungan, justru bisa memperburuk keadaan.",
    "Orang seharusnya tidak terlalu mengandalkan pasangan mereka untuk kebahagiaan pribadi.",
    "Ketika pasanganmu berubah menjadi seseorang yang berbeda, kamu berhak untuk memilih apakah akan tetap bersama atau tidak.",
    "Perselingkuhan bisa dimaafkan jika pasangan menunjukkan penyesalan yang tulus dan berusaha memperbaiki hubungan.",
    "Mempunyai hubungan dengan lebih dari satu orang sekaligus (polyamory) adalah hal yang sah dan tidak salah secara moral.",
    "Orang yang terlalu bergantung pada pasangan untuk kebahagiaannya cenderung menghambat perkembangan pribadi mereka.",
    "Mengungkapkan perasaan terlalu banyak dalam hubungan bisa membuat pasangan merasa tertekan.",
    "Tidak perlu selalu setuju dengan pasangan tentang segala hal untuk memiliki hubungan yang sehat.",
    "Seorang teman yang benar-benar peduli tidak akan pernah meninggalkan kita, apa pun yang terjadi.",
    "Persahabatan sejati tidak mungkin terjadi jika ada perasaan iri antara teman.",
    "Persahabatan bisa bertahan meskipun salah satu pihak pernah berkhianat.",
    "Uang dan persahabatan tidak boleh dicampur; salah satu pasti akan hancur.",
    "Dalam persahabatan, kejujuran lebih penting daripada menjaga perasaan.",
    "Terkadang, lebih baik memutuskan hubungan dengan teman yang tidak lagi sejalan dengan kita.",
    "Persahabatan jarak jauh biasanya tidak akan bertahan lama.",
    "Teman yang baik harus selalu mendukung keputusan kita, bahkan jika itu salah.",
    "Memilih teman berdasarkan status sosial atau keuangan adalah hal yang wajar.",
    "Teman lama lebih berharga daripada teman baru, meskipun tidak lagi sering berkomunikasi.",
    "Terkadang, orang yang kita anggap teman hanya memanfaatkan kita untuk keuntungan pribadi mereka.",
    "Dalam pertemanan, membicarakan teman di belakang mereka adalah hal yang tidak bisa dihindari.",
    "Lebih baik memiliki banyak teman yang dangkal daripada hanya satu teman yang benar-benar dekat.",
    "Teman dari lawan jenis biasanya akan menimbulkan masalah jika salah satu mulai memiliki perasaan romantis.",
    "Memutuskan pertemanan karena perbedaan pandangan politik atau agama adalah hal yang dapat dibenarkan.",
    "Teman yang terlalu jujur cenderung lebih banyak menyakiti daripada membantu.",
    "Tidak semua teman layak diberi kesempatan kedua setelah mereka melakukan kesalahan besar.",
    "Ketika kita sukses, teman sejati adalah mereka yang tetap mendukung tanpa merasa iri.",
    "Teman seharusnya selalu mendahulukan kita dibandingkan dengan hubungan romantis mereka.",
    "Teman yang sering meminjam uang dan tidak mengembalikannya lebih baik dihindari.",
    "Dalam persahabatan, loyalitas lebih penting daripada kejujuran.",
    "Teman yang berubah karena pengaruh pasangan mereka bukanlah teman sejati.",
    "Tidak semua teman layak diajak untuk berbagi masalah pribadi.",
    "Teman yang berbeda latar belakang budaya sulit untuk memahami kita sepenuhnya.",
    "Teman yang terlalu sering mengkritik kita sebenarnya tidak tulus dalam persahabatan.",
    "Persahabatan tidak bisa bertahan jika salah satu pihak tidak mau berkompromi.",
    "Membatalkan rencana dengan teman demi pekerjaan adalah hal yang dapat dibenarkan.",
    "Teman yang hanya hadir saat kita sedang senang seharusnya tidak dianggap teman sejati.",
    "Terkadang, kita harus membatasi hubungan dengan teman yang terlalu bergantung secara emosional.",
    "Persahabatan dengan mantan pasangan romantis hampir selalu akan menimbulkan masalah.",
    "Cinta tidak harus selalu dibalas untuk dianggap tulus.",
    "Ketidaksetiaan dalam hubungan bisa dimaafkan jika masih ada cinta.",
    "Pasangan memiliki hak untuk mengetahui setiap aspek kehidupan pribadi kita.",
    "Hubungan tanpa pernikahan lebih fleksibel dan sehat dibandingkan hubungan yang diikat pernikahan.",
    "Perbedaan agama dalam hubungan lebih sering menjadi penyebab konflik daripada pengayaan.",
    "Pasangan harus memiliki akses ke media sosial masing-masing untuk membangun kepercayaan.",
    "Ketidaksetaraan penghasilan antara pasangan bisa menjadi penyebab utama keretakan hubungan.",
    "Tidak ada yang salah dengan menjalin hubungan demi keuntungan finansial.",
    "Hubungan yang sehat membutuhkan salah satu pihak untuk mendominasi.",
    "Dalam hubungan, mempertahankan kebebasan pribadi lebih penting daripada mengikuti keinginan pasangan.",
    "Seks adalah komponen yang lebih penting daripada cinta dalam hubungan jangka panjang.",
    "Pasangan yang tidak bisa memenuhi kebutuhan emosional kita sebaiknya digantikan.",
    "Hubungan jarak jauh lebih banyak membawa penderitaan daripada kebahagiaan.",
    "Tidak ada salahnya memiliki hubungan terbuka selama kedua pihak setuju.",
    "Perbedaan pandangan politik yang ekstrem tidak seharusnya menjadi penghalang dalam hubungan.",
    "Pasangan harus selalu mengutamakan keluarga mereka dibandingkan pasangannya.",
    "Ketertarikan fisik lebih penting daripada kecocokan emosional dalam awal hubungan.",
    "Menikah untuk memenuhi harapan keluarga lebih baik daripada hidup sendiri.",
    "Pasangan yang tidak sepaham tentang memiliki anak seharusnya tidak melanjutkan hubungan.",
    "Percintaan masa lalu harus selalu diceritakan kepada pasangan untuk menjaga kejujuran."
];

// Menampilkan pertanyaan secara acak
function showRandomQuestion() {
  const randomIndex = Math.floor(Math.random() * questions.length);
  const questionText = questions[randomIndex];
  document.querySelector(".question").textContent = questionText;
}

// Mengubah pertanyaan ketika tombol "NEXT CARD" ditekan
document.getElementById("next-btn").addEventListener("click", showRandomQuestion);

// Menampilkan pertanyaan pertama saat halaman dimuat
window.onload = showRandomQuestion;
